export { default as AuthRoutes } from './auth/index.js'
export { default as CartRoutes } from './cart/index.js'
export { default as ChatRoutes } from './chat/index.js'
export { default as ProductRoutes } from './product/index.js'
export { default as UserRoutes } from './user/index.js'
export { default as ViewRoutes } from './views/index.js'
export { default as LoggerRoutes } from './logger/index.js'